
name: Merge

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_AMI_USERS: ${{secrets.AWS_AMI_USERS}}
on:
  push:
    branches: [ main ]

jobs:
  ami_creation_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Hashicorp Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.8.3

    - name: Download Packer plugin libraries
      run: packer init packerfile-ami.pkr.hcl

    - name: Building Packer Template
      run: packer build  -var 'ami_users=${{env.AWS_AMI_USERS}}' packerfile-ami.pkr.hcl 2>&1 | sudo tee name.txt; tail -2 name.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }' >> ami_name.txt

    - name: Create new launch template
      run: cat ami_name.txt | while read ami; do aws ec2 create-launch-template-version --launch-template-name webapp-launch-template --version-description v1 --source-version 1 --launch-template-data "ImageId=$ami"; done

    - name: Update the autoscaling group  
      run: aws autoscaling update-auto-scaling-group --auto-scaling-group-name webapp-autoscaling-group --launch-template LaunchTemplateName=webapp-launch-template,Version='$Latest'

    - name: Instance refresh
      run: aws autoscaling start-instance-refresh --auto-scaling-group-name webapp-autoscaling-group
